# Spring properties
spring:
  application:
     name: edge-service  # Service registers under this name

ribbon:
  serverListRefreshInterval: 1000
  ConnectTimeout: 6000
  ReadTimeout: 3000
  SocketTimeout: 6000
  #NFLoadBalancerRuleClassName: com.edge.filter.StickySessionRule //comenté esto
  
zuul:
  ignoredServices: '*'
  routes:
    greetings:
      path: /estudiante/**
      serviceId: web-estudiante
      stripPrefix: false
      #url: http://localhost:2222/ qutié esto

web-estudiante.ribbon.NFLoadBalancerRuleClassName: com.edge.filter.StickySessionRule

# Discovery Server Access
eureka:
  client:
    #registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/


server:
  port: 8080   # HTTP (Tomcat) port
  
  